export const SKILL_OPTIONS = [
  "JavaScript",
  "TypeScript",
  "React",
  "Node.js",
  "HTML/CSS",
  "Python",
  "Java",
  "C++",
  "Git",
  "Docker",
  "Go",
  "Rust",
  "Kotlin",
  "Swift",
  "PHP",
  "Ruby",
  "C#",
  "Scala",
  "Perl",
  "R",
  "Dart",
  "Flutter",
  "React Native",
  "Vue.js",
  "Angular",
  "Svelte",
  "Next.js",
  "Nuxt.js",
  "Express.js",
  "NestJS",
  "Spring Boot",
  "Django",
  "Flask",
  "Laravel",
  "Ruby on Rails",
  ".NET",
  "GraphQL",
  "Apollo",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "Redis",
  "Elasticsearch",
  "AWS",
  "Azure",
  "GCP",
  "Kubernetes",
  "Terraform",
  "Ansible",
  "Jenkins",
  "CI/CD",
  "WebAssembly",
  "TensorFlow",
  "PyTorch",
  "Machine Learning",
  "Blockchain",
  "Solidity",
  "Electron",
];

export const PAGINATION = {
  currentPage: 1,
  itemsPerPage: 10,
  totalPages: 0,
  total: 0,
}

export const DEFAULT_CANDIDATE_FORM = {
  full_name: "",
  phone_number: "",
  email: "",
  interview_level: "intern",
  gender: "",
  preferred_stack: "",
  skills: [],
};

export const STATUS = {
  pending: "pending",
  interviewed: "interviewed",
  hired: "hired",
  rejected: "rejected",
};
export const LEVEL_OPTIONS = [
  { value: "intern", label: "Intern" },
  { value: "fresher", label: "Fresher" },
  { value: "junior", label: "Junior" },
  { value: "middle", label: "Middle" },
  { value: "senior", label: "Senior" },
  { value: "expert", label: "Expert" },
];

export const TYPES = [
  { value: "questions", label: "Ngôn ngữ lập trình" },
  { value: "instruments", label: "Kỹ năng mềm" },
];
